import {
  Student,
  Course,
  Batch,
  MonthlyAttendance,
  BlossomMonthlyPayment,
  DropoutRecord,
  Assessment,
  AssessmentMark,
  CourseCompletion,
  StudentOutcome,
  AuditLog,
  OrgProfile,
  SystemSettings,
} from './types';

export const initialOrgProfile: OrgProfile = {
  orgName: 'Unicom TIC Training Centre',
  tagline: 'Center for Technology, Innovation & Blossom Trust Scholars',
  regNumber: 'TIC-LK/2026/8842',
  trustName: 'Blossom Trust Educational Foundation',
  email: 'admin@unicomtic.org',
  phone: '+94 21 222 4589 / +94 77 123 4567',
  address: 'No. 360, Innovation Square, Jaffna, Sri Lanka',
  website: 'https://unicomtic.org',
  currencySymbol: 'LKR',
  establishedYear: '2021',
};

export const initialCourses: Course[] = [
  {
    id: 'CRS-01',
    code: 'TIC-FED',
    name: 'Frontend Developer',
    description: 'HTML5, CSS3, Modern JavaScript, React 19, Tailwind CSS, TypeScript and UI Design.',
    durationMonths: 4,
    isActive: true,
  },
  {
    id: 'CRS-02',
    code: 'TIC-FSD',
    name: 'Full Stack Developer',
    description: 'Next.js App Router, Node.js, PostgreSQL, Supabase, Cloud Deployment and REST/GraphQL APIs.',
    durationMonths: 6,
    isActive: true,
  },
];

export const initialBatches: Batch[] = [
  {
    id: 'BAT-01',
    name: 'Batch 01 (2026 Term I)',
    courseId: 'CRS-02',
    courseName: 'Full Stack Developer',
    startDate: '2026-01-15',
    endDate: '2026-07-15',
    status: 'Completed',
  },
  {
    id: 'BAT-02',
    name: 'Batch 02 (2026 Term II)',
    courseId: 'CRS-02',
    courseName: 'Full Stack Developer',
    startDate: '2026-06-01',
    status: 'Active',
  },
  {
    id: 'BAT-03',
    name: 'Batch 03 (Frontend Special)',
    courseId: 'CRS-01',
    courseName: 'Frontend Developer',
    startDate: '2026-07-01',
    status: 'Active',
  },
];

export const initialStudents: Student[] = [
  {
    id: 'STU-1001',
    utNumber: 'UT-2026-001',
    fullName: 'Karthik Sivakumar',
    nic: '200185403211',
    dob: '2001-05-14',
    gender: 'Male',
    phone: '+94 77 452 1180',
    whatsapp: '+94 77 452 1180',
    email: 'karthik.s@unicomtic.org',
    address: 'Point Pedro Road, Nallur, Jaffna',
    district: 'Jaffna',
    emergencyContact: {
      name: 'Sivakumar Kandasamy (Father)',
      phone: '+94 77 991 2234',
      relationship: 'Father',
    },
    batchId: 'BAT-02',
    batchName: 'Batch 02 (2026 Term II)',
    courseId: 'CRS-02',
    courseName: 'Full Stack Developer',
    photoUrl: '',
    isBlossomTrust: true,
    currentStatus: 'Active',
    bankDetails: {
      bankName: 'Commercial Bank of Ceylon',
      branchName: 'Jaffna Main Branch',
      branchCode: '045',
      accountNumber: '8004529103',
      beneficiaryName: 'Karthik Sivakumar',
      district: 'Jaffna',
    },
    blossomApplication: {
      parentsOccupation: 'Farmer / Day Laborer',
      familyIncome: 35000,
      familyMembersCount: 5,
      siblingsCount: 2,
      financialDifficulties: 'Father recovering from illness; sole earner supporting younger siblings in school.',
      accommodationExpense: 5000,
      foodExpense: 18000,
      declarationSigned: true,
      verificationStatus: 'Verified',
      verifiedAt: '2026-05-28',
    },
    createdAt: '2026-05-20',
    updatedAt: '2026-08-30',
  },
  {
    id: 'STU-1002',
    utNumber: 'UT-2026-002',
    fullName: 'Ananya Tharmalingam',
    nic: '200271904552',
    dob: '2002-09-22',
    gender: 'Female',
    phone: '+94 71 884 9231',
    whatsapp: '+94 71 884 9231',
    email: 'ananya.t@unicomtic.org',
    address: 'Main Street, Chavakachcheri',
    district: 'Jaffna',
    emergencyContact: {
      name: 'Tharmalingam R. (Father)',
      phone: '+94 71 332 4411',
      relationship: 'Father',
    },
    batchId: 'BAT-02',
    batchName: 'Batch 02 (2026 Term II)',
    courseId: 'CRS-02',
    courseName: 'Full Stack Developer',
    photoUrl: '',
    isBlossomTrust: true,
    currentStatus: 'Active',
    bankDetails: {
      bankName: 'Bank of Ceylon (BOC)',
      branchName: 'Chavakachcheri Branch',
      branchCode: '018',
      accountNumber: '7341908221',
      beneficiaryName: 'Ananya Tharmalingam',
      district: 'Jaffna',
    },
    blossomApplication: {
      parentsOccupation: 'Weaving & Tailoring',
      familyIncome: 28000,
      familyMembersCount: 4,
      siblingsCount: 1,
      financialDifficulties: 'Mother is single parent earning irregular wages.',
      accommodationExpense: 4000,
      foodExpense: 16000,
      declarationSigned: true,
      verificationStatus: 'Verified',
      verifiedAt: '2026-05-29',
    },
    createdAt: '2026-05-22',
    updatedAt: '2026-08-30',
  },
  {
    id: 'STU-1003',
    utNumber: 'UT-2026-003',
    fullName: 'Dharshini Ragunathan',
    nic: '200366104928',
    dob: '2003-11-05',
    gender: 'Female',
    phone: '+94 75 601 8820',
    whatsapp: '+94 75 601 8820',
    email: 'dharshini.r@gmail.com',
    address: 'Beach Road, Gurunagar, Jaffna',
    district: 'Jaffna',
    emergencyContact: {
      name: 'Ragunathan S.',
      phone: '+94 75 221 0099',
      relationship: 'Brother',
    },
    batchId: 'BAT-03',
    batchName: 'Batch 03 (Frontend Special)',
    courseId: 'CRS-01',
    courseName: 'Frontend Developer',
    isBlossomTrust: false,
    currentStatus: 'Active',
    createdAt: '2026-06-15',
    updatedAt: '2026-08-25',
  },
  {
    id: 'STU-1004',
    utNumber: 'UT-2026-004',
    fullName: 'Piratheepan Mohan',
    nic: '200155209118',
    dob: '2001-03-19',
    gender: 'Male',
    phone: '+94 70 334 1199',
    whatsapp: '+94 70 334 1199',
    email: 'pira.mohan@unicomtic.org',
    address: 'KKS Road, Chunnakam',
    district: 'Jaffna',
    emergencyContact: {
      name: 'Mohan P.',
      phone: '+94 70 998 1234',
      relationship: 'Father',
    },
    batchId: 'BAT-02',
    batchName: 'Batch 02 (2026 Term II)',
    courseId: 'CRS-02',
    courseName: 'Full Stack Developer',
    isBlossomTrust: true,
    currentStatus: 'Active',
    bankDetails: {
      bankName: 'National Savings Bank (NSB)',
      branchName: 'Chunnakam Branch',
      branchCode: '041',
      accountNumber: '20098174591',
      beneficiaryName: 'Piratheepan Mohan',
      district: 'Jaffna',
    },
    blossomApplication: {
      parentsOccupation: 'Carpenter',
      familyIncome: 32000,
      familyMembersCount: 6,
      siblingsCount: 3,
      financialDifficulties: 'Large dependent family.',
      accommodationExpense: 3000,
      foodExpense: 20000,
      declarationSigned: true,
      verificationStatus: 'Verified',
      verifiedAt: '2026-05-30',
    },
    createdAt: '2026-05-25',
    updatedAt: '2026-08-30',
  },
  {
    id: 'STU-1005',
    utNumber: 'UT-2026-005',
    fullName: 'Raveendran Sarujan',
    nic: '200211809934',
    dob: '2002-07-11',
    gender: 'Male',
    phone: '+94 77 665 4432',
    whatsapp: '+94 77 665 4432',
    email: 'sarujan.r@gmail.com',
    address: 'Hospital Road, Kilinochchi',
    district: 'Kilinochchi',
    emergencyContact: {
      name: 'Raveendran K.',
      phone: '+94 77 112 8899',
      relationship: 'Father',
    },
    batchId: 'BAT-02',
    batchName: 'Batch 02 (2026 Term II)',
    courseId: 'CRS-02',
    courseName: 'Full Stack Developer',
    isBlossomTrust: true,
    currentStatus: 'Dropout',
    bankDetails: {
      bankName: 'People\'s Bank',
      branchName: 'Kilinochchi Branch',
      branchCode: '033',
      accountNumber: '089200194819',
      beneficiaryName: 'Raveendran Sarujan',
      district: 'Kilinochchi',
    },
    createdAt: '2026-05-20',
    updatedAt: '2026-08-15',
  },
  {
    id: 'STU-1006',
    utNumber: 'UT-2026-006',
    fullName: 'Abinaya Kuganesan',
    nic: '200088902194',
    dob: '2000-12-08',
    gender: 'Female',
    phone: '+94 76 998 7712',
    whatsapp: '+94 76 998 7712',
    email: 'abinaya.k@unicomtic.org',
    address: 'Vavuniya Town, Vavuniya',
    district: 'Vavuniya',
    emergencyContact: {
      name: 'Kuganesan V.',
      phone: '+94 76 554 1122',
      relationship: 'Father',
    },
    batchId: 'BAT-01',
    batchName: 'Batch 01 (2026 Term I)',
    courseId: 'CRS-02',
    courseName: 'Full Stack Developer',
    isBlossomTrust: true,
    currentStatus: 'Completed',
    bankDetails: {
      bankName: 'Hatton National Bank (HNB)',
      branchName: 'Vavuniya Branch',
      branchCode: '071',
      accountNumber: '071020098412',
      beneficiaryName: 'Abinaya Kuganesan',
      district: 'Vavuniya',
    },
    createdAt: '2026-01-10',
    updatedAt: '2026-07-20',
  },
  {
    id: 'STU-1007',
    utNumber: 'UT-2026-007',
    fullName: 'Jeyaruban Thanushan',
    nic: '200177301982',
    dob: '2001-08-17',
    gender: 'Male',
    phone: '+94 77 129 0088',
    whatsapp: '+94 77 129 0088',
    email: 'thanushan.j@gmail.com',
    address: 'Kandy Road, Jaffna',
    district: 'Jaffna',
    emergencyContact: {
      name: 'Thanushan J.',
      phone: '+94 77 887 6655',
      relationship: 'Brother',
    },
    batchId: 'BAT-01',
    batchName: 'Batch 01 (2026 Term I)',
    courseId: 'CRS-02',
    courseName: 'Full Stack Developer',
    isBlossomTrust: false,
    currentStatus: 'Completed',
    createdAt: '2026-01-10',
    updatedAt: '2026-07-20',
  },
];

export const initialMonthlyAttendance: MonthlyAttendance[] = [
  // August 2026 (2026-08)
  {
    id: 'ATT-2026-08-001',
    studentId: 'STU-1001',
    utNumber: 'UT-2026-001',
    studentName: 'Karthik Sivakumar',
    batchId: 'BAT-02',
    courseName: 'Full Stack Developer',
    year: 2026,
    month: '2026-08',
    attendancePercentage: 92.5,
    status: 'Good Attendance',
    recordedBy: 'Trainer Niranjan',
    updatedAt: '2026-08-31',
  },
  {
    id: 'ATT-2026-08-002',
    studentId: 'STU-1002',
    utNumber: 'UT-2026-002',
    studentName: 'Ananya Tharmalingam',
    batchId: 'BAT-02',
    courseName: 'Full Stack Developer',
    year: 2026,
    month: '2026-08',
    attendancePercentage: 88.0,
    status: 'Good Attendance',
    recordedBy: 'Trainer Niranjan',
    updatedAt: '2026-08-31',
  },
  {
    id: 'ATT-2026-08-003',
    studentId: 'STU-1003',
    utNumber: 'UT-2026-003',
    studentName: 'Dharshini Ragunathan',
    batchId: 'BAT-03',
    courseName: 'Frontend Developer',
    year: 2026,
    month: '2026-08',
    attendancePercentage: 95.0,
    status: 'Good Attendance',
    recordedBy: 'Trainer Pavithra',
    updatedAt: '2026-08-31',
  },
  {
    id: 'ATT-2026-08-004',
    studentId: 'STU-1004',
    utNumber: 'UT-2026-004',
    studentName: 'Piratheepan Mohan',
    batchId: 'BAT-02',
    courseName: 'Full Stack Developer',
    year: 2026,
    month: '2026-08',
    attendancePercentage: 72.0, // LOW ATTENDANCE (<80%) -> Payment = 0!
    status: 'Low Attendance',
    recordedBy: 'Trainer Niranjan',
    updatedAt: '2026-08-31',
  },
  {
    id: 'ATT-2026-08-005',
    studentId: 'STU-1005',
    utNumber: 'UT-2026-005',
    studentName: 'Raveendran Sarujan',
    batchId: 'BAT-02',
    courseName: 'Full Stack Developer',
    year: 2026,
    month: '2026-08',
    attendancePercentage: 45.0, // Dropout in August
    status: 'Critical Attendance',
    recordedBy: 'Trainer Niranjan',
    updatedAt: '2026-08-15',
  },

  // July 2026 (2026-07)
  {
    id: 'ATT-2026-07-001',
    studentId: 'STU-1001',
    utNumber: 'UT-2026-001',
    studentName: 'Karthik Sivakumar',
    batchId: 'BAT-02',
    courseName: 'Full Stack Developer',
    year: 2026,
    month: '2026-07',
    attendancePercentage: 86.0,
    status: 'Good Attendance',
    recordedBy: 'Trainer Niranjan',
    updatedAt: '2026-07-31',
  },
  {
    id: 'ATT-2026-07-002',
    studentId: 'STU-1002',
    utNumber: 'UT-2026-002',
    studentName: 'Ananya Tharmalingam',
    batchId: 'BAT-02',
    courseName: 'Full Stack Developer',
    year: 2026,
    month: '2026-07',
    attendancePercentage: 84.5,
    status: 'Good Attendance',
    recordedBy: 'Trainer Niranjan',
    updatedAt: '2026-07-31',
  },
  {
    id: 'ATT-2026-07-004',
    studentId: 'STU-1004',
    utNumber: 'UT-2026-004',
    studentName: 'Piratheepan Mohan',
    batchId: 'BAT-02',
    courseName: 'Full Stack Developer',
    year: 2026,
    month: '2026-07',
    attendancePercentage: 88.0, // Eligible in July
    status: 'Good Attendance',
    recordedBy: 'Trainer Niranjan',
    updatedAt: '2026-07-31',
  },
  {
    id: 'ATT-2026-07-005',
    studentId: 'STU-1005',
    utNumber: 'UT-2026-005',
    studentName: 'Raveendran Sarujan',
    batchId: 'BAT-02',
    courseName: 'Full Stack Developer',
    year: 2026,
    month: '2026-07',
    attendancePercentage: 82.0,
    status: 'Good Attendance',
    recordedBy: 'Trainer Niranjan',
    updatedAt: '2026-07-31',
  },
];

export const initialBlossomPayments: BlossomMonthlyPayment[] = [
  // August 2026
  {
    id: 'PAY-2026-08-001',
    studentId: 'STU-1001',
    utNumber: 'UT-2026-001',
    studentName: 'Karthik Sivakumar',
    year: 2026,
    month: '2026-08',
    attendancePercentage: 92.5,
    isEligible: true,
    amount: 15000,
    status: 'Paid',
    paymentDate: '2026-08-31',
    referenceNo: 'BTR-202608-001',
    notes: 'Transferred to Commercial Bank account',
  },
  {
    id: 'PAY-2026-08-002',
    studentId: 'STU-1002',
    utNumber: 'UT-2026-002',
    studentName: 'Ananya Tharmalingam',
    year: 2026,
    month: '2026-08',
    attendancePercentage: 88.0,
    isEligible: true,
    amount: 15000,
    status: 'Paid',
    paymentDate: '2026-08-31',
    referenceNo: 'BTR-202608-002',
    notes: 'Transferred to BOC account',
  },
  {
    id: 'PAY-2026-08-004',
    studentId: 'STU-1004',
    utNumber: 'UT-2026-004',
    studentName: 'Piratheepan Mohan',
    year: 2026,
    month: '2026-08',
    attendancePercentage: 72.0,
    isEligible: false,
    ineligibilityReason: 'Low Attendance (72.0% < 80.0% threshold)',
    amount: 0, // CRITICAL RULE: Low attendance = LKR 0!
    status: 'Not Eligible',
    notes: 'Support payment forfeited due to attendance below 80%',
  },
  {
    id: 'PAY-2026-08-005',
    studentId: 'STU-1005',
    utNumber: 'UT-2026-005',
    studentName: 'Raveendran Sarujan',
    year: 2026,
    month: '2026-08',
    attendancePercentage: 45.0,
    isEligible: false,
    ineligibilityReason: 'Student Dropped Out in August 2026',
    amount: 0,
    status: 'Not Eligible',
    notes: 'Future payments suspended due to dropout',
  },

  // July 2026
  {
    id: 'PAY-2026-07-001',
    studentId: 'STU-1001',
    utNumber: 'UT-2026-001',
    studentName: 'Karthik Sivakumar',
    year: 2026,
    month: '2026-07',
    attendancePercentage: 86.0,
    isEligible: true,
    amount: 15000,
    status: 'Paid',
    paymentDate: '2026-07-31',
    referenceNo: 'BTR-202607-001',
  },
  {
    id: 'PAY-2026-07-002',
    studentId: 'STU-1002',
    utNumber: 'UT-2026-002',
    studentName: 'Ananya Tharmalingam',
    year: 2026,
    month: '2026-07',
    attendancePercentage: 84.5,
    isEligible: true,
    amount: 15000,
    status: 'Paid',
    paymentDate: '2026-07-31',
    referenceNo: 'BTR-202607-002',
  },
  {
    id: 'PAY-2026-07-004',
    studentId: 'STU-1004',
    utNumber: 'UT-2026-004',
    studentName: 'Piratheepan Mohan',
    year: 2026,
    month: '2026-07',
    attendancePercentage: 88.0,
    isEligible: true,
    amount: 15000,
    status: 'Paid',
    paymentDate: '2026-07-31',
    referenceNo: 'BTR-202607-004',
  },
];

export const initialDropouts: DropoutRecord[] = [
  {
    id: 'DRP-001',
    studentId: 'STU-1005',
    utNumber: 'UT-2026-005',
    studentName: 'Raveendran Sarujan',
    batchId: 'BAT-02',
    courseId: 'CRS-02',
    courseName: 'Full Stack Developer',
    dropoutMonth: '2026-08',
    reason: 'Financial Problem',
    rejoinPossibility: 'Medium',
    remarks: 'Needed to work full-time to support family medical expenses. May rejoin in 2027.',
    recordedAt: '2026-08-15',
  },
];

export const initialAssessments: Assessment[] = [
  {
    id: 'ASM-01',
    courseId: 'CRS-02',
    batchId: 'BAT-02',
    title: 'Assignment 01: Responsive Portfolio',
    category: 'Assignment',
    maxMarks: 100,
    createdAt: '2026-06-20',
  },
  {
    id: 'ASM-02',
    courseId: 'CRS-02',
    batchId: 'BAT-02',
    title: 'Project 01: E-Commerce REST API',
    category: 'Project',
    maxMarks: 100,
    createdAt: '2026-07-15',
  },
  {
    id: 'ASM-03',
    courseId: 'CRS-02',
    batchId: 'BAT-02',
    title: 'Presentation: System Architecture',
    category: 'Presentation',
    maxMarks: 50,
    createdAt: '2026-08-10',
  },
  {
    id: 'ASM-04',
    courseId: 'CRS-02',
    batchId: 'BAT-02',
    title: 'Final Capstone Project (Full Stack Next.js)',
    category: 'Final Project',
    maxMarks: 100,
    createdAt: '2026-08-25',
  },
];

export const initialAssessmentMarks: AssessmentMark[] = [
  {
    id: 'MRK-01',
    assessmentId: 'ASM-01',
    studentId: 'STU-1001',
    marksObtained: 94,
    feedback: 'Excellent semantic HTML & Tailwind design.',
    gradedAt: '2026-06-25',
  },
  {
    id: 'MRK-02',
    assessmentId: 'ASM-01',
    studentId: 'STU-1002',
    marksObtained: 88,
    feedback: 'Clean code and responsive layout.',
    gradedAt: '2026-06-25',
  },
  {
    id: 'MRK-03',
    assessmentId: 'ASM-02',
    studentId: 'STU-1001',
    marksObtained: 92,
    feedback: 'Thorough Postgres schema with clean authentication.',
    gradedAt: '2026-07-20',
  },
  {
    id: 'MRK-04',
    assessmentId: 'ASM-02',
    studentId: 'STU-1002',
    marksObtained: 85,
    feedback: 'Good error handling.',
    gradedAt: '2026-07-20',
  },
  {
    id: 'MRK-05',
    assessmentId: 'ASM-03',
    studentId: 'STU-1001',
    marksObtained: 48,
    feedback: 'Outstanding technical presentation.',
    gradedAt: '2026-08-15',
  },
];

export const initialCompletions: CourseCompletion[] = [
  {
    id: 'CMP-001',
    studentId: 'STU-1006',
    utNumber: 'UT-2026-006',
    studentName: 'Abinaya Kuganesan',
    courseId: 'CRS-02',
    courseName: 'Full Stack Developer',
    batchId: 'BAT-01',
    completionDate: '2026-07-15',
    finalResult: 'Distinction',
    finalProjectName: 'HealthCare Clinic Appointment Portal',
    githubLink: 'https://github.com/abinaya/clinic-portal',
    overallGrade: 'A',
    certificateIssued: true,
  },
  {
    id: 'CMP-002',
    studentId: 'STU-1007',
    utNumber: 'UT-2026-007',
    studentName: 'Jeyaruban Thanushan',
    courseId: 'CRS-02',
    courseName: 'Full Stack Developer',
    batchId: 'BAT-01',
    completionDate: '2026-07-15',
    finalResult: 'Passed',
    finalProjectName: 'Agritech Farmer Market System',
    githubLink: 'https://github.com/thanushan/agritech-market',
    overallGrade: 'B',
    certificateIssued: true,
  },
];

export const initialStudentOutcomes: StudentOutcome[] = [
  {
    id: 'OUT-001',
    studentId: 'STU-1006',
    utNumber: 'UT-2026-006',
    studentName: 'Abinaya Kuganesan',
    isBlossomTrust: true,
    outcomeStatus: 'Employed',
    outcomeDate: '2026-08-01',
    companyOrInstitution: 'CodeGen International',
    jobTitle: 'Associate Software Engineer',
    remarks: 'Hired within 3 weeks of graduation with starting salary LKR 120,000.',
    updatedAt: '2026-08-05',
  },
  {
    id: 'OUT-002',
    studentId: 'STU-1007',
    utNumber: 'UT-2026-007',
    studentName: 'Jeyaruban Thanushan',
    isBlossomTrust: false,
    outcomeStatus: 'Internship',
    outcomeDate: '2026-08-10',
    companyOrInstitution: 'WSO2 Sri Lanka',
    jobTitle: 'Full Stack Engineering Intern',
    remarks: '6-month industrial internship contract.',
    updatedAt: '2026-08-12',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'LOG-01',
    userName: 'Admin User',
    userRole: 'Admin',
    action: 'Student Registered',
    entity: 'Student',
    recordId: 'UT-2026-001',
    details: 'Enrolled Karthik Sivakumar (Blossom Trust: Yes)',
    timestamp: '2026-05-20 10:15:00',
  },
  {
    id: 'LOG-02',
    userName: 'Trainer Niranjan',
    userRole: 'Trainer',
    action: 'Attendance Recorded',
    entity: 'Attendance',
    recordId: '2026-08',
    details: 'Submitted Batch 02 August attendance register',
    timestamp: '2026-08-31 17:30:00',
  },
  {
    id: 'LOG-03',
    userName: 'Blossom Officer',
    userRole: 'Blossom Trust Officer',
    action: 'Payment Processed',
    entity: 'Blossom Payment',
    recordId: '2026-08',
    details: 'Processed August 2026 disbursements; LKR 0 for UT-2026-004 due to <80% attendance',
    timestamp: '2026-08-31 18:00:00',
  },
];

export const initialSystemSettings: SystemSettings = {
  attendanceGoodThreshold: 80,
  attendanceLowThreshold: 60,
  blossomMonthlyMax: 15000,
  paymentEligibilityAttendanceThreshold: 80,
  courses: initialCourses,
  batches: initialBatches,
  dropoutReasons: [
    'Financial Problem',
    'Employment',
    'Higher Studies',
    'Family Problem',
    'Health/Personal',
    'Migration',
    'Lack of Interest',
    'Unknown',
  ],
  outcomeStatuses: [
    'Employed',
    'Self Employed',
    'Higher Studies',
    'Internship',
    'Looking for Job',
    'Unemployed',
    'Foreign Employment',
    'Other',
  ],
  grades: ['A', 'B', 'C', 'D', 'E'],
};
